
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1500x844")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 844,
    width = 1500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    750.0,
    421.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=59.0,
    y=757.0,
    width=222.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=639.0,
    y=757.0,
    width=222.0,
    height=40.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1219.0,
    y=757.0,
    width=222.0,
    height=40.0
)

canvas.create_text(
    575.0,
    111.0,
    anchor="nw",
    text="Favor Message:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    159.0,
    anchor="nw",
    text="Like Message:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    207.0,
    anchor="nw",
    text="Normal Message:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    255.0,
    anchor="nw",
    text="Dislike Message:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    303.0,
    anchor="nw",
    text="Hate Message:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    489.0,
    anchor="nw",
    text="Like Item ID:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    588.0,
    anchor="nw",
    text="Dislike Item ID:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    687.0,
    anchor="nw",
    text="Other:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    537.0,
    anchor="nw",
    text="Normal Item ID:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    636.0,
    anchor="nw",
    text="Hate Item ID:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

canvas.create_text(
    575.0,
    441.0,
    anchor="nw",
    text="Favor Item ID:",
    fill="#FFFFFF",
    font=("Kanit Light", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    909.0,
    131.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=769.5,
    y=114.0,
    width=279.0,
    height=33.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    909.0,
    179.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=769.5,
    y=162.0,
    width=279.0,
    height=33.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    909.0,
    227.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=769.5,
    y=210.0,
    width=279.0,
    height=33.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    909.0,
    275.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=769.5,
    y=258.0,
    width=279.0,
    height=33.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    909.0,
    323.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=769.5,
    y=306.0,
    width=279.0,
    height=33.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    909.0,
    461.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=769.5,
    y=444.0,
    width=279.0,
    height=33.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    909.0,
    509.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=769.5,
    y=492.0,
    width=279.0,
    height=33.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    909.0,
    608.5,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=769.5,
    y=591.0,
    width=279.0,
    height=33.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    909.0,
    707.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=769.5,
    y=690.0,
    width=279.0,
    height=33.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    909.0,
    557.5,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=769.5,
    y=540.0,
    width=279.0,
    height=33.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    909.0,
    656.5,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=769.5,
    y=639.0,
    width=279.0,
    height=33.0
)

canvas.create_text(
    59.0,
    107.0,
    anchor="nw",
    text="Mod Name:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    154.0,
    anchor="nw",
    text="Author:\n",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    201.0,
    anchor="nw",
    text="Version:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    248.0,
    anchor="nw",
    text="Description:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    295.0,
    anchor="nw",
    text="UniqueID:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    342.0,
    anchor="nw",
    text="NexusID:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    436.0,
    anchor="nw",
    text="Format:\n",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    483.0,
    anchor="nw",
    text="NPC Name:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    534.0,
    anchor="nw",
    text="Location:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    577.0,
    anchor="nw",
    text="Position X:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    624.0,
    anchor="nw",
    text="Position Y:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    59.0,
    671.0,
    anchor="nw",
    text="Direction:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    393.0,
    131.5,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=253.5,
    y=114.0,
    width=279.0,
    height=33.0
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    393.0,
    178.5,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=253.5,
    y=161.0,
    width=279.0,
    height=33.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    393.0,
    225.5,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_14.place(
    x=253.5,
    y=208.0,
    width=279.0,
    height=33.0
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    393.0,
    272.5,
    image=entry_image_15
)
entry_15 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_15.place(
    x=253.5,
    y=255.0,
    width=279.0,
    height=33.0
)

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    393.0,
    319.5,
    image=entry_image_16
)
entry_16 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_16.place(
    x=253.5,
    y=302.0,
    width=279.0,
    height=33.0
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    393.0,
    366.5,
    image=entry_image_17
)
entry_17 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_17.place(
    x=253.5,
    y=349.0,
    width=279.0,
    height=33.0
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    393.0,
    460.5,
    image=entry_image_18
)
entry_18 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_18.place(
    x=253.5,
    y=443.0,
    width=279.0,
    height=33.0
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    393.0,
    507.5,
    image=entry_image_19
)
entry_19 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_19.place(
    x=253.5,
    y=490.0,
    width=279.0,
    height=33.0
)

entry_image_20 = PhotoImage(
    file=relative_to_assets("entry_20.png"))
entry_bg_20 = canvas.create_image(
    326.5,
    554.5,
    image=entry_image_20
)
entry_20 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_20.place(
    x=253.5,
    y=537.0,
    width=146.0,
    height=33.0
)

entry_image_21 = PhotoImage(
    file=relative_to_assets("entry_21.png"))
entry_bg_21 = canvas.create_image(
    281.5,
    601.5,
    image=entry_image_21
)
entry_21 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_21.place(
    x=253.5,
    y=584.0,
    width=56.0,
    height=33.0
)

entry_image_22 = PhotoImage(
    file=relative_to_assets("entry_22.png"))
entry_bg_22 = canvas.create_image(
    281.5,
    648.5,
    image=entry_image_22
)
entry_22 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_22.place(
    x=253.5,
    y=631.0,
    width=56.0,
    height=33.0
)

entry_image_23 = PhotoImage(
    file=relative_to_assets("entry_23.png"))
entry_bg_23 = canvas.create_image(
    281.5,
    695.5,
    image=entry_image_23
)
entry_23 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_23.place(
    x=253.5,
    y=678.0,
    width=56.0,
    height=33.0
)

canvas.create_text(
    1120.9998779296875,
    107.0,
    anchor="nw",
    text="NPC Age:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.0,
    154.0,
    anchor="nw",
    text="Behavior:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.0001220703125,
    201.0,
    anchor="nw",
    text="Personality:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.000244140625,
    248.0,
    anchor="nw",
    text="Attitude:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.0003662109375,
    295.0,
    anchor="nw",
    text="Gender:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.00048828125,
    342.0,
    anchor="nw",
    text="Dateting:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.0006103515625,
    389.0,
    anchor="nw",
    text="Session Birthday",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

canvas.create_text(
    1121.000732421875,
    480.0,
    anchor="nw",
    text="Birthday:",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1297.0,
    y=114.0,
    width=110.0,
    height=35.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=1297.0001220703125,
    y=161.0,
    width=110.0,
    height=35.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1297.000244140625,
    y=208.0,
    width=110.0,
    height=35.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=1297.0003662109375,
    y=255.0,
    width=110.0,
    height=35.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=1297.00048828125,
    y=302.0,
    width=110.0,
    height=35.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=1297.0006103515625,
    y=349.0,
    width=110.0,
    height=35.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=1297.000732421875,
    y=396.0,
    width=110.0,
    height=35.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=1297.0008544921875,
    y=487.0,
    width=110.0,
    height=35.0
)

canvas.create_text(
    1166.0,
    643.0,
    anchor="nw",
    text="Sprites Set",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

entry_image_24 = PhotoImage(
    file=relative_to_assets("entry_24.png"))
entry_bg_24 = canvas.create_image(
    1230.5,
    708.5,
    image=entry_image_24
)
entry_24 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_24.place(
    x=1157.5,
    y=691.0,
    width=146.0,
    height=33.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=1310.0,
    y=679.0,
    width=97.0,
    height=78.0
)

canvas.create_text(
    1166.0,
    540.0,
    anchor="nw",
    text="Portraits Set",
    fill="#FFFFFF",
    font=("Kanit Light", 29 * -1)
)

entry_image_25 = PhotoImage(
    file=relative_to_assets("entry_25.png"))
entry_bg_25 = canvas.create_image(
    1230.5,
    605.5,
    image=entry_image_25
)
entry_25 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_25.place(
    x=1157.5,
    y=588.0,
    width=146.0,
    height=33.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=1310.0,
    y=576.0,
    width=97.0,
    height=78.0
)

canvas.create_text(
    379.0,
    30.0,
    anchor="nw",
    text="NPC Maker",
    fill="#FFFFFF",
    font=("Kanit Light", 48 * -1)
)
window.resizable(False, False)
window.mainloop()
